clusterID: "test"
organization: ""
clusterValues: false

apps:
  linkerd2-cni:
    appName: linkerd2-cni
    chartName: linkerd2-cni
    catalog: giantswarm
    enabled: true
    namespace: linkerd-cni
    namespaceConfig:
      labels:
        linkerd.io/cni-resource: "true"
        config.linkerd.io/admission-webhooks: disabled
    # used by renovate
    # repo: giantswarm/linkerd2-cni-app
    version: 1.4.1
    # User values can be provided via a ConfigMap or Secret for each individual app
    userConfig: {}
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []
  linkerd-control-plane:
    appName: linkerd-control-plane
    annotations: {}
    chartName: linkerd-control-plane
    catalog: giantswarm
    enabled: true
    namespace: linkerd
    namespaceConfig:
      annotations:
        linkerd.io/inject: disabled
      labels:
        linkerd.io/is-control-plane: "true"
        config.linkerd.io/admission-webhooks: disabled
        linkerd.io/control-plane-ns: linkerd
    # used by renovate
    # repo: giantswarm/linkerd-control-plane-app
    version: 1.4.0
    userConfig: {}
    extraConfigs: []
    dependsOn: linkerd2-cni
  linkerd-viz:
    appName: linkerd-viz
    annotations: {}
    chartName: linkerd-viz
    catalog: giantswarm
    enabled: true
    namespace: linkerd-viz
    namespaceConfig:
      labels:
        linkerd.io/extension: viz
    # used by renovate
    # repo: giantswarm/linkerd-viz-app
    version: 1.5.0
    userConfig: {}
    extraConfigs: []
    dependsOn: linkerd-control-plane
  linkerd-multicluster:
    appName: linkerd-multicluster
    annotations:
      app-operator.giantswarm.io/depends-on: linkerd-control-plane
    chartName: linkerd-multicluster
    catalog: giantswarm
    enabled: false
    namespace: linkerd-multicluster
    namespaceConfig:
      labels:
        linkerd.io/extension: multicluster
    # used by renovate
    # repo: giantswarm/linkerd-multicluster-app
    version: 0.11.1
    userConfig: {}
    extraConfigs: []
    dependsOn: linkerd-control-plane
  linkerd-multicluster-link:
    appName: linkerd-multicluster-link
    annotations: {}
    chartName: linkerd-multicluster-link
    catalog: giantswarm
    enabled: false
    namespace: linkerd-multicluster
    namespaceConfig:
      labels:
        linkerd.io/extension: multicluster
    # used by renovate
    # repo: giantswarm/linkerd-multicluster-link-app
    version: 0.11.1
    userConfig: {}
    extraConfigs: []
    dependsOn: linkerd-multicluster
