apiVersion: v1
kind: ConfigMap
metadata:
  name: abc12-service-mesh-bundle-user-values
  namespace: org-test
data:
  values: |
    clusterID: abc12
    organization: test
    apps:
      linkerd-control-plane:
        userConfig:
          secret:
            values: |
              identity:
                issuer:
                  tls:
                    crtPEM: |
                      <contents of the issuer.crt file>
                    keyPEM: |
                      <contents of the issuer.key file>
              identityTrustAnchorsPEM: |
                <contents of the ca.crt file>
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: abc12-service-mesh-bundle
  namespace: org-test
  labels:
    app.kubernetes.io/name: service-mesh-bundle
    giantswarm.io/cluster: abc12
    app-operator.giantswarm.io/version: 0.0.0
spec:
  catalog: giantswarm
  name: service-mesh-bundle
  version: 0.3.1
  userConfig:
    configMap:
      name: abc12-service-mesh-bundle-user-values
      namespace: org-test
  kubeConfig:
    inCluster: true
  namespace: org-test
